#!/bin/bash
# see https://feriman.com/stop-shell-script-overlaps-how-to-prevent-multiple-instances-from-running-simultaneously/
PreventMultipleRun() {
    lockfile="/tmp/$(basename "$0").lock"
    [ -f "$lockfile" ] && ps -p $(cat $lockfile) > /dev/null && echo "$(basename "$0") is still running." && exit || echo $$ > $lockfile
}
PreventMultipleRun
# Directory to save screenshots
save_dir=~/Pictures/Screenshots
# Create the directory if it doesn't exist
mkdir -p "$save_dir"
# Filename with timestamp
filename="$save_dir/$(date +%Y-%m-%d_%H-%M-%S).png"

# Select region with slurp, capture with grim, save and copy to clipboard
region=$(slurp -d -b '#000000b0' -c '#00000000')
if [ -n "$region" ]; then
    grim -g "$region" "$filename" && \
        wl-copy < "$filename" && \
        {
            # Send clickable notification and handle response
            response=$(notify-send "Screenshot Taken" "Click to edit with Swappy" \
                --action="edit=Edit with Swappy" \
                --action="open=Open Folder" \
                --wait)

            case "$response" in
                "edit")
                    swappy -f "$filename"
                    ;;
                "open")
                    xdg-open "$(dirname "$filename")"
                    ;;
            esac
        } &
fi
