# :schema https://yazi-rs.github.io/schemas/keymap.json
# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = "<C-u>"
run = "seek -5"
desc = "Seek up 5 units in the preview"

[[manager.prepend_keymap]]
on = "<C-d>"
run = "seek 5"
desc = "Seek down 5 units in the preview"

[[manager.prepend_keymap]]
on = "<A-k>"
run = "arrow -50%"
desc = "Move cursor up half page"

[[manager.prepend_keymap]]
on = "<A-j>"
run = "arrow 50%"
desc = "Move cursor down half page"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"
