git:

    paging:
      pager: delta --dark --paging=never

gui:

  theme:
    activeBorderColor:
    - '#00a381'
    - bold
    inactiveBorderColor:
    - '#a5adcb'
    optionsTextColor:
    - '#8aadf4'
    selectedLineBgColor:
    # 天鵞絨 びろうど
    - '#2f5d50'
    cherryPickedCommitBgColor:
    - '#494d64'
    cherryPickedCommitFgColor:
    - '#00a381'
    unstagedChangesColor:
    - '#ed8796'
    defaultFgColor:
    - '#cad3f5'
    searchingActiveBorderColor:
    - '#eed49f'

  authorColors:
    'Ray Guo': '#b7bdf8'
    'ergou': '#b7bdf8'
    '*': '#ed8796'
