git:
  paging:
    pager: delta --dark --paging=never
gui:
  theme:
    defaultFgColor:
      - "#cad3f5"
    cherryPickedCommitFgColor:
      - "#8aadf4"
    cherryPickedCommitBgColor:
      - "#f0c6c6"
    activeBorderColor:
      - "#f5a97f"
      - "bold"
    unstagedChangesColor:
      - "#ed8796"
    selectedLineBgColor:
      - "#494d64"
    searchingActiveBorderColor:
      - "#f5a97f"
      - "bold"
    optionsTextColor:
      - "#8aadf4"
    inactiveBorderColor:
      - "#8aadf4"


  authorColors:
    'Ray Guo': '#8aadf4'
    'ergou': '#8aadf4'
    '*': '#ed8796'

customCommands:
  - key: "v"
    context: "localBranches"
    loadingText: "Checking out GitHub Pull Request..."
    command: "gh pr checkout {{.Form.PullRequestNumber}}"
    prompts:
      - type: "menuFromCommand"
        title: "Which PR do you want to check out?"
        key: "PullRequestNumber"
        command: >-
          gh pr list --json number,title,headRefName,updatedAt
          --template '{{`{{range .}}{{printf "#%v: %s - %s (%s)" .number .title .headRefName (timeago .updatedAt)}}{{end}}`}}'
        filter: '#(?P<number>[0-9]+): (?P<title>.+) - (?P<ref_name>[^ ]+).*'
        valueFormat: '{{.number}}'
        labelFormat: '{{"#" | black | bold}}{{.number | white | bold}} {{.title | yellow | bold}}{{" [" | black | bold}}{{.ref_name | green}}{{"]" | black | bold}}'
  
