git:
    paging:
      colorArg: always
      pager: delta --dark --paging=never
      useConfig: false
gui:

  theme:
    activeBorderColor:
    - '#a6da95'
    - bold
    inactiveBorderColor:
    - '#a5adcb'
    optionsTextColor:
    - '#8aadf4'
    selectedLineBgColor:
    - '#005243'
    cherryPickedCommitBgColor:
    - '#494d64'
    cherryPickedCommitFgColor:
    - '#a6da95'
    unstagedChangesColor:
    - '#ed8796'
    defaultFgColor:
    - '#cad3f5'
    searchingActiveBorderColor:
    - '#eed49f'

  authorColors:
    'Ray Guo': '#b7bdf8'
    '*': '#ed8796'
