require("conf.vars")
require("conf.monitors")
require("conf.autostart")
require("conf.env")
require("conf.general")
require("conf.animations")
require("conf.keybindings")
require("conf.window-rules")
