#!/usr/bin/env bash

# Git worktree helpers (inspired by DHH)
# https://gist.github.com/dhh/18575558fc5ee10f15b6cd3e108ed844

set -euo pipefail

cwd="$(pwd)"
worktree="$(basename "$cwd")"
root="${worktree%%--*}"
branch="${worktree#*--}"
force_flag=""

if [[ "$root" == "$worktree" ]]; then
  echo "Not inside a worktree directory"
  exit 1
fi

printf "Remove worktree and branch '%s'? [y/N] " "$branch"
read -r answer
[[ "$answer" != [yY] ]] && exit 0

root_path="$(dirname "$cwd")/$root"

# see https://gist.github.com/catapulta/5fa16111817d6b653c1e5ff4608c7567
if ! git diff --quiet || ! git diff --cached --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
  echo "Warning: '$branch' has modified or untracked files."
  read -q "?Are you sure? This will discard all changes. [y/N] " || return
  echo
  force_flag="--force"
fi

git -C "$root_path" worktree remove "$cwd" "$force_flag"
git -C "$root_path" branch -D "$branch"

if [[ -n $TMUX ]]; then
  $(dirname "$0")/sessionizer "$root_path"
  if tmux list-sessions 2>/dev/null | grep -q "^${worktree}:"; then
    tmux kill-session -t "$worktree"
  fi
else
  cd "$root_path"
fi
