#!/usr/bin/env bash
# Get the current session name
current_session=$(tmux display-message -p '#S')

# Present the sorted list, excluding the current session
# FIXME: The ctrl-d spawn a new sh and does not delete the session
selected_session=$(_get_sessions | grep -v "^$current_session$" | fzf \
  --no-preview \
  --cycle \
  --header-first \
  --header "Switch Session (Ctrl+D to remove)" \
  --bind "ctrl-d:execute-silent(tmux kill-session -t {+})+reload(_get_sessions | grep -v \"^$current_session$\" || true)")

# Switch to the selected session if one is chosen
if [ -n "$selected_session" ]; then
  # Set the 'updated_at' environment variable with the current timestamp
  tmux set-environment -t "$selected_session" updated_at "$(date +%Y-%m-%dT%H:%M:%S)"

  # Switch to the selected session
  tmux switch-client -t "$selected_session"
fi
