#!/usr/bin/env bash

# Get the current session name
current_session=$(tmux display-message -p '#S')

# Present the sorted list, excluding the current session
selected_session=$(_get_sessions | grep -v "^$current_session$" | fzf --no-preview --cycle --header-first --header "Delete Session")

# Kill the selected session if one is chosen
if [ -n "$selected_session" ]; then
  tmux kill-session -t "$selected_session"
fi

