#!/usr/bin/env bash

set -e

if [ -z "$DOTFILES" ]; then 
  echo "DOTFILE dir not found"
  exit 1
fi

__flavors=(frappe latte macchiato mocha)

__color="blue"

## YAZI ##
__yazi_url="https://raw.githubusercontent.com/catppuccin/yazi/main/themes/"

for flavor in "${__flavors[@]}"; do
  yazi_flavor_file="$DOTFILES/yazi/flavors/${flavor}.yazi/flavor.toml"
  echo "Downloading yazi $flavor..."
  curl "${__yazi_url}${flavor}/catppuccin-${flavor}-${__color}.toml" -o "$yazi_flavor_file"
  echo "Commenting out overall bg setting..."
  sed -i 's/^overall = { bg = ".*" }/# &/' "$yazi_flavor_file"
done


## Bat ##
__bat_url="https://raw.githubusercontent.com/catppuccin/bat/main/themes/"
for flavor in "${__flavors[@]}"; do
  yazi_theme_file="$DOTFILES/yazi/flavors/${flavor}.yazi/tmtheme.xml"
  bat_theme_file="$DOTFILES/bat/themes/Catppuccin ${flavor^}.tmTheme"
  echo "Downloading bash $flavor..."
  curl "${__bat_url}Catppuccin%20${flavor^}.tmTheme" -o "${bat_theme_file}"
  echo "Download finished, copying to yazi themes..."
  cp "${bat_theme_file}" "${yazi_theme_file}"
done


