# alias
alias ls='exa -l'
alias cat='bat'
alias pnd='pnpm dev'
alias nv='nvim'
alias configjava='sudo update-alternatives --config java'
alias configzsh='nvim ~/.zshrc'
alias reload='source ~/.zshrc'
alias cdp='cd $HOME/work/rmvfy-vue-portal'
alias aptupdate='sudo apt update && sudo apt upgrade -y'
alias pvm='sudo update-alternatives --config php'
alias fe='ESLINT_USE_FLAT_CONFIG=true $HOME/.local/share/nvim/mason/bin/eslint_d restart'
alias ufe='ESLINT_USE_FLAT_CONFIG= $HOME/.local/share/nvim/mason/bin/eslint_d restart'
