name: lua style check

on: push

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: JohnnyMorganz/stylua-action@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            version: latest
            # CLI arguments
            args: --check ./nvim --config-path ./nvim/stylua.toml
